/**
 * Template Resolver Service
 *
 * Handles resolution of template executions for entities.
 */

import { resolve } from 'node:path';

import type { CodepurifyRuntime } from './codepurify-runtime';
import type { ResolvedCodepurifyConfig } from '@/config/global/types/codepurify.config.types';
import type { IEntityConfig } from '@/config/entity/types/entity';
import type { CodepurifyTemplateRegistration, CodepurifyTemplatesFile } from '@/config/global/types/codepurify.templates.types';
import type { LoadedEntity } from './entity-loader';

export interface TemplateExecutionContext {
  /** Global configuration */
  globalConfig: ResolvedCodepurifyConfig;
  /** Loaded entity configurations */
  entityConfigs: LoadedEntity[];
  /** Entity contexts (generated by createEntityContext) */
  entityContexts: EntityContext[];
}

export interface EntityContext {
  /** Entity configuration */
  entity: IEntityConfig;
  /** Discovered entity metadata */
  discovered: LoadedEntity['discovered'];
  /** Computed entity metadata */
  metadata: {
    /** Entity key in various formats */
    keys: {
      camel: string;
      pascal: string;
      kebab: string;
      snake: string;
    };
    /** Entity group information */
    group: {
      key: string;
      pascal: string;
    };
  };
}

export interface TemplateExecution {
  /** Template configuration */
  template: CodepurifyTemplateRegistration;
  /** Entity context for this execution */
  entityContext: EntityContext;
  /** Resolved output path */
  outputPath: string;
  /** Template source information */
  source: {
    templatePath: string;
    absoluteTemplatePath: string;
  };
}

export class TemplateResolver {
  constructor(private readonly runtime: CodepurifyRuntime) {}

  /**
   * Resolves template executions for all entities.
   *
   * @param context - Template execution context
   * @returns Array of template executions
   */
  async resolveTemplateExecutions(context: TemplateExecutionContext): Promise<TemplateExecution[]> {
    const executions: TemplateExecution[] = [];

    for (const entityContext of context.entityContexts) {
      const entityExecutions = await this.resolveEntityTemplateExecutions(entityContext, context.globalConfig);
      executions.push(...entityExecutions);
    }

    return executions;
  }

  /**
   * Resolves template executions for a single entity.
   *
   * @param entityContext - Entity context
   * @param globalConfig - Global configuration
   * @returns Array of template executions for the entity
   */
  private async resolveEntityTemplateExecutions(
    entityContext: EntityContext,
    globalConfig: ResolvedCodepurifyConfig,
  ): Promise<TemplateExecution[]> {
    const executions: TemplateExecution[] = [];
    const templateFiles = entityContext.entity.templates || [];

    for (const templateFile of templateFiles) {
      try {
        // Load the template registry file to get individual template registrations
        const templateRegistry = await this.loadTemplateRegistry(templateFile, globalConfig);

        // Resolve each template registration in the registry
        for (const template of templateRegistry.templates) {
          const execution = await this.resolveSingleTemplateExecution(template, entityContext, globalConfig);
          executions.push(execution);
        }
      } catch (error) {
        throw new Error(
          `Failed to resolve template registry for entity '${entityContext.entity.key}': ${error instanceof Error ? error.message : String(error)}`,
        );
      }
    }

    return executions;
  }

  /**
   * Loads a template registry file.
   *
   * @param templateFile - Template file configuration
   * @param globalConfig - Global configuration
   * @returns Loaded template registry
   */
  private async loadTemplateRegistry(
    templateFile: CodepurifyTemplatesFile,
    globalConfig: ResolvedCodepurifyConfig,
  ): Promise<CodepurifyTemplatesFile> {
    // For now, return the template file as-is
    // In a full implementation, this would load the actual template registry file
    return templateFile;
  }

  /**
   * Resolves a single template execution.
   *
   * @param template - Template configuration
   * @param entityContext - Entity context
   * @param globalConfig - Global configuration
   * @returns Template execution
   */
  private async resolveSingleTemplateExecution(
    template: CodepurifyTemplateRegistration,
    entityContext: EntityContext,
    globalConfig: ResolvedCodepurifyConfig,
  ): Promise<TemplateExecution> {
    // Resolve template path
    const templatePath = this.resolveTemplatePath(template, globalConfig);
    const absoluteTemplatePath = resolve(globalConfig.rootDir, templatePath);

    // Resolve output path
    const outputPath = this.resolveOutputPath(template, entityContext, globalConfig);

    return {
      template,
      entityContext,
      outputPath,
      source: {
        templatePath,
        absoluteTemplatePath,
      },
    };
  }

  /**
   * Resolves the template file path.
   *
   * @param template - Template configuration
   * @param globalConfig - Global configuration
   * @returns Template file path
   */
  private resolveTemplatePath(template: CodepurifyTemplateRegistration, globalConfig: ResolvedCodepurifyConfig): string {
    const templatesRoot = './code/templates'; // Default templates root
    return resolve(templatesRoot, template.templatePath);
  }

  /**
   * Resolves the output path for a template execution.
   *
   * @param template - Template configuration
   * @param entityContext - Entity context
   * @param globalConfig - Global configuration
   * @returns Output file path
   */
  private resolveOutputPath(
    template: CodepurifyTemplateRegistration,
    entityContext: EntityContext,
    globalConfig: ResolvedCodepurifyConfig,
  ): string {
    const outputDir = globalConfig.outputDir || './src/generated';

    // Resolve output folder using entity context
    const outputFolder = this.resolveOutputFolder(template, entityContext);

    // Resolve file name using entity context
    const fileName = this.resolveFileName(template, entityContext);

    return resolve(outputDir, outputFolder, fileName);
  }

  /**
   * Resolves the output folder for a template.
   *
   * @param template - Template configuration
   * @param entityContext - Entity context
   * @returns Output folder path
   */
  private resolveOutputFolder(template: CodepurifyTemplateRegistration, entityContext: EntityContext): string {
    if (!template.outputFolder) {
      return '';
    }

    // Process output folder array with entity context
    return template.outputFolder.map((segment) => this.processTemplateSegment(segment, entityContext)).join('/');
  }

  /**
   * Resolves the file name for a template.
   *
   * @param template - Template configuration
   * @param entityContext - Entity context
   * @returns File name
   */
  private resolveFileName(template: CodepurifyTemplateRegistration, entityContext: EntityContext): string {
    if (!template.fileName) {
      return `${entityContext.metadata.keys.kebab}.${template.name}.ts`;
    }

    // Process file name with entity context
    return this.processTemplateSegment(template.fileName, entityContext);
  }

  /**
   * Processes a template segment with entity context substitution.
   *
   * @param segment - Template segment
   * @param entityContext - Entity context
   * @returns Processed segment
   */
  private processTemplateSegment(segment: unknown, entityContext: EntityContext): string {
    if (typeof segment === 'string') {
      return segment;
    }

    // Handle function-based segments
    if (typeof segment === 'function') {
      try {
        const result = segment(entityContext.metadata.keys);
        return typeof result === 'string' ? result : String(result);
      } catch (error) {
        throw new Error(`Failed to process template segment: ${error instanceof Error ? error.message : String(error)}`);
      }
    }

    // Handle object-based segments (like file() helper)
    if (typeof segment === 'object' && segment !== null) {
      return this.processObjectSegment(segment as Record<string, unknown>, entityContext);
    }

    return String(segment);
  }

  /**
   * Processes object-based template segments.
   *
   * @param segment - Object segment
   * @param entityContext - Entity context
   * @returns Processed segment
   */
  private processObjectSegment(segment: Record<string, unknown>, entityContext: EntityContext): string {
    // Handle file helper objects
    if (segment.prefix || segment.suffix || segment.ext) {
      let result = entityContext.metadata.keys.kebab;

      if (segment.prefix) {
        result = `${segment.prefix}${result}`;
      }

      if (segment.suffix) {
        result = `${result}${segment.suffix}`;
      }

      if (segment.ext) {
        const ext = String(segment.ext).replace(/^\./, '');
        result = `${result}.${ext}`;
      }

      return result;
    }

    return String(segment);
  }
}
