"""CLI option names and help text."""

from __future__ import annotations

OPT_SPEC = "spec"
OPT_LANGUAGE = "language"
OPT_TEMPLATES = "templates"
OPT_TEMPLATE_PACKAGE = "template-package"
OPT_SELECT = "select"
OPT_TEMPLATE = "template"
OPT_OUT = "out"
OPT_ONLY = "only"
OPT_STRICT = "strict"
OPT_DRY_RUN = "dry-run"
OPT_FORCE = "force"
OPT_WATCH = "watch"
OPT_FORMAT = "format"
OPT_RUN_HOOKS = "run-hooks"
OPT_SKIP_STATIC = "skip-static"
OPT_SHOW_CONTEXT = "show-context"
OPT_SHOW_IMPORTS = "show-imports"
OPT_SHOW_DEPENDENCIES = "show-dependencies"
OPT_SHOW_PATHS = "show-paths"
OPT_JSON = "json"
OPT_QUIET = "quiet"
OPT_VERBOSE = "verbose"
OPT_DEBUG = "debug"
OPT_INTERACTIVE = "interactive"

HELP_SPEC = "Path to compiled Codepot spec."
HELP_LANGUAGE = "Target language."
HELP_TEMPLATES = "Templates directory."
HELP_TEMPLATE_PACKAGE = "Path to a Codepotx template package directory."
HELP_SELECT = "Filter by selection, for example models.each."
HELP_TEMPLATE = "Filter by template ID from codepotx.yaml."
HELP_OUT = "Output root."
HELP_ONLY = "Comma-separated template IDs to include."
HELP_STRICT = "Treat warnings as errors."
HELP_DRY_RUN = "Preview files without writing."
HELP_FORCE = "Overwrite even when files already exist."
HELP_WATCH = "Watch spec/templates and re-run on changes."
HELP_FORMAT = "Run formatter after emit."
HELP_RUN_HOOKS = "Run configured template package hooks after emit."
HELP_SKIP_STATIC = "Skip copying static files."
HELP_SHOW_CONTEXT = "Show template context details."
HELP_SHOW_IMPORTS = "Show inferred imports."
HELP_SHOW_DEPENDENCIES = "Show inferred dependencies."
HELP_SHOW_PATHS = "Show resolved output paths only."
HELP_JSON = "Output machine-readable JSON."
HELP_QUIET = "Suppress normal output."
HELP_VERBOSE = "Show extra details."
HELP_DEBUG = "Raise errors with traceback."
HELP_INTERACTIVE = "Prompt for missing values."
