"""CLI option names and help text."""

from __future__ import annotations

OPT_SPEC = "spec"
OPT_LANGUAGE = "language"
OPT_TEMPLATES = "templates"
OPT_OUT = "out"
OPT_ONLY = "only"
OPT_STRICT = "strict"
OPT_DRY_RUN = "dry-run"
OPT_FORCE = "force"
OPT_WATCH = "watch"
OPT_SHOW_CONTEXT = "show-context"
OPT_SHOW_PATHS = "show-paths"
OPT_JSON = "json"
OPT_QUIET = "quiet"
OPT_VERBOSE = "verbose"
OPT_DEBUG = "debug"
OPT_INTERACTIVE = "interactive"

HELP_SPEC = "Path to compiled Codepot spec."
HELP_LANGUAGE = "Target language."
HELP_TEMPLATES = "Templates directory."
HELP_OUT = "Output root."
HELP_ONLY = "Comma-separated paths.yaml group IDs."
HELP_STRICT = "Treat warnings as errors."
HELP_DRY_RUN = "Preview files without writing."
HELP_FORCE = "Overwrite even when files already exist."
HELP_WATCH = "Watch spec/templates and re-run on changes."
HELP_SHOW_CONTEXT = "Show template context details."
HELP_SHOW_PATHS = "Show resolved output paths only."
HELP_JSON = "Output machine-readable JSON."
HELP_QUIET = "Suppress normal output."
HELP_VERBOSE = "Show extra details."
HELP_DEBUG = "Raise errors with traceback."
HELP_INTERACTIVE = "Prompt for missing values."
