export const SchemaAccess = {
  /**
   * Safe for public/API output.
   */
  public: 'public',

  /**
   * Visible to authenticated users only.
   */
  auth: 'auth',

  /**
   * Visible only in owner/admin/private contexts.
   */
  private: 'private',

  /**
   * Sensitive credential/security data.
   * Hidden from generated public models, docs examples, logs, and toString.
   */
  secret: 'secret',

  /**
   * Internal application/service field.
   * Hidden from public/default generated outputs.
   */
  internal: 'internal',

  /**
   * System-managed field.
   * Usually generated by DB/server, not accepted from client input.
   */
  system: 'system',
} as const;

export type SchemaAccess = (typeof SchemaAccess)[keyof typeof SchemaAccess];

const HIDDEN_BY_DEFAULT_ACCESS = new Set<SchemaAccess>([SchemaAccess.secret, SchemaAccess.internal, SchemaAccess.system]);

const SENSITIVE_ACCESS = new Set<SchemaAccess>([SchemaAccess.secret]);

const CLIENT_WRITABLE_ACCESS = new Set<SchemaAccess>([SchemaAccess.public, SchemaAccess.auth, SchemaAccess.private]);

export function isHiddenByDefault(access?: SchemaAccess): boolean {
  return access ? HIDDEN_BY_DEFAULT_ACCESS.has(access) : false;
}

export function isSensitiveAccess(access?: SchemaAccess): boolean {
  return access ? SENSITIVE_ACCESS.has(access) : false;
}

export function isClientWritableAccess(access?: SchemaAccess): boolean {
  return access ? CLIENT_WRITABLE_ACCESS.has(access) : true;
}

export function isSystemManagedAccess(access?: SchemaAccess): boolean {
  return access === SchemaAccess.system;
}

export function isInternalAccess(access?: SchemaAccess): boolean {
  return access === SchemaAccess.internal || access === SchemaAccess.system;
}
