"""CLI application constants."""

CLI_APP_NAME = "dart-py"
CLI_APP_HELP = "Custom Dart SDK generator for OpenAPI specs."

CLI_OPTION_DEBUG = "--debug"
CLI_OPTION_INPUT = "--input"
CLI_OPTION_INPUT_SHORT = "-i"
CLI_OPTION_OUTPUT = "--output"
CLI_OPTION_OUTPUT_SHORT = "-o"

CLI_OPTION_DART_OUTPUT = "--dart-output"
CLI_OPTION_DOCS_OUTPUT = "--docs-output"
CLI_OPTION_PACKAGE_NAME = "--package-name"

CLI_OPTION_DRY_RUN = "--dry-run"
CLI_OPTION_CLEAN = "--clean"
CLI_OPTION_FORMAT = "--format"
CLI_OPTION_STRICT_FORMAT = "--strict-format"
CLI_OPTION_TOOLING = "--tooling"
CLI_OPTION_FORCE_TOOLING = "--force-tooling"
CLI_OPTION_INTERACTIVE = "--interactive"
CLI_OPTION_INTERACTIVE_SHORT = "-i"
CLI_OPTION_YES = "--yes"
CLI_OPTION_YES_SHORT = "-y"

CLI_HELP_DEBUG = "Enable debug logs."
CLI_HELP_INPUT = "OpenAPI JSON/YAML file."
CLI_HELP_DART_OUTPUT = "Dart SDK lib output dir."
CLI_HELP_DOCS_OUTPUT = "Markdown docs output dir."
CLI_HELP_PACKAGE_NAME = "Dart package name."
CLI_HELP_DRY_RUN = "Run without writing files."
CLI_HELP_CLEAN = "Clean output folders first."
CLI_HELP_FORMAT = "Run dart format on generated files."
CLI_HELP_STRICT_FORMAT = "Fail if dart format fails."
CLI_HELP_TOOLING = "Generate tooling files (.vscode/settings.json, analysis_options.yaml)."
CLI_HELP_FORCE_TOOLING = "Overwrite existing tooling files."
CLI_HELP_INTERACTIVE = "Run interactive generation wizard."
CLI_HELP_YES = "Accept defaults and run non-interactively."
