"""CLI prompt constants."""

PROMPT_GENERATION_TARGET = "What do you want to generate?"
PROMPT_CLEAN_OUTPUT = "Clean output before generating?"
PROMPT_TOOLING = "Generate tooling files?"
PROMPT_FORMAT = "Run dart format?"
PROMPT_GENERATE_DOCS = "Generate docs?"
PROMPT_GENERATE_DART = "Generate Dart SDK?"
PROMPT_GENERATE_FIELDS = "Generate Dart fields?"
PROMPT_GENERATE_ENUMS = "Generate Dart enums?"
PROMPT_GENERATE_CLASSES = "Generate Dart classes?"

GENERATION_TARGET_EVERYTHING = "Everything"
GENERATION_TARGET_DART_ONLY = "Dart SDK only"
GENERATION_TARGET_DOCS_ONLY = "Docs only"
GENERATION_TARGET_ENUMS_ONLY = "Enums only"
GENERATION_TARGET_FIELDS_ONLY = "Fields only"
GENERATION_TARGET_CLASSES_ONLY = "Classes only"
GENERATION_TARGET_CUSTOM = "Custom"
