/**
 * @file db-definition.types.ts
 * @description Generic DB definition contracts for SQL, TypeORM, MongoDB, and Mongoose-style entity metadata.
 */

// //////////////////////////////////////////////////////////////////////////////
//  CORE KEYS
// //////////////////////////////////////////////////////////////////////////////

export type EntityKey<TEntity> = Extract<keyof TEntity, string>;

export type BaseEntityKey<TEntity, TBase> = Extract<keyof TEntity & keyof TBase, string>;

export type EntityOwnKey<TEntity, TBase = never> = TBase extends never
  ? EntityKey<TEntity>
  : Exclude<EntityKey<TEntity>, BaseEntityKey<TEntity, TBase>>;

// //////////////////////////////////////////////////////////////////////////////
//  DB PROVIDERS
// //////////////////////////////////////////////////////////////////////////////

export type DBProvider = 'sql' | 'typeorm' | 'mongo' | 'mongoose' | 'custom';

export type SQLDialect = 'postgres' | 'mysql' | 'mariadb' | 'sqlite' | 'mssql' | 'cockroachdb' | 'custom';

export type MongoProvider = 'mongodb' | 'mongoose';

// //////////////////////////////////////////////////////////////////////////////
//  ENTITY META
// //////////////////////////////////////////////////////////////////////////////

export interface EntityMeta {
  name: string;
  module: string;
  schema: string;
  tableName: string;
  collectionName?: string;
  route: string;
  entityClass: string;
  repositoryToken?: string;
}

// //////////////////////////////////////////////////////////////////////////////
//  COMMON COLUMN / FIELD TYPES
// //////////////////////////////////////////////////////////////////////////////

export type DBScalarType =
  | 'uuid'
  | 'string'
  | 'varchar'
  | 'char'
  | 'text'
  | 'boolean'
  | 'int'
  | 'integer'
  | 'bigint'
  | 'float'
  | 'double'
  | 'decimal'
  | 'date'
  | 'time'
  | 'timestamp'
  | 'datetime'
  | 'json'
  | 'jsonb'
  | 'enum'
  | 'simple-enum'
  | 'array'
  | 'object'
  | 'objectId'
  | 'mixed'
  | 'custom';

export type GeneratedStrategy = 'uuid' | 'increment' | 'identity' | 'rowid' | 'custom';

export type ReferentialAction = 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION' | 'SET DEFAULT';

export interface BaseFieldConfig {
  /**
   * Logical DB type.
   */
  type: DBScalarType;

  /**
   * Physical DB column/property name.
   */
  name?: string;

  /**
   * Whether the value can be null.
   */
  nullable?: boolean;

  /**
   * Whether the value must be unique.
   */
  unique?: boolean;

  /**
   * Whether the value is indexed.
   */
  index?: boolean;

  /**
   * Default DB/application value.
   */
  default?: unknown;

  /**
   * Field-level comment for migrations/docs.
   */
  comment?: string;

  /**
   * Whether field is generated by DB/runtime.
   */
  generated?: boolean | GeneratedStrategy;

  /**
   * Whether field is selected by default at ORM level.
   */
  select?: boolean;

  /**
   * Whether field is insertable.
   */
  insert?: boolean;

  /**
   * Whether field is updateable.
   */
  update?: boolean;
}

// //////////////////////////////////////////////////////////////////////////////
//  SQL / TYPEORM FIELD CONFIG
// //////////////////////////////////////////////////////////////////////////////

export interface SQLFieldConfig extends BaseFieldConfig {
  length?: number;
  precision?: number;
  scale?: number;
  unsigned?: boolean;
  enum?: readonly string[] | Record<string, string | number>;
  array?: boolean;
  primary?: boolean;
  columnDefinition?: string;
  transformer?: unknown;
}

export interface TypeORMFieldConfig extends SQLFieldConfig {
  typeorm?: {
    type?: string;
    primary?: boolean;
    primaryGeneratedColumn?: boolean | GeneratedStrategy;
    createDateColumn?: boolean;
    updateDateColumn?: boolean;
    deleteDateColumn?: boolean;
    versionColumn?: boolean;
    columnOptions?: Record<string, unknown>;
  };
}

// //////////////////////////////////////////////////////////////////////////////
//  MONGO / MONGOOSE FIELD CONFIG
// //////////////////////////////////////////////////////////////////////////////

export interface MongoFieldConfig extends BaseFieldConfig {
  bsonType?: string;
  required?: boolean;
  sparse?: boolean;
  immutable?: boolean;
  ref?: string;
}

export interface MongooseFieldConfig extends MongoFieldConfig {
  mongoose?: {
    type?: unknown;
    required?: boolean;
    ref?: string;
    enum?: readonly string[] | Record<string, string | number>;
    minlength?: number;
    maxlength?: number;
    min?: number;
    max?: number;
    trim?: boolean;
    lowercase?: boolean;
    uppercase?: boolean;
    select?: boolean;
    immutable?: boolean;
    validate?: unknown;
    get?: unknown;
    set?: unknown;
  };
}

// //////////////////////////////////////////////////////////////////////////////
//  CUSTOM FIELD CONFIG
// //////////////////////////////////////////////////////////////////////////////

export interface CustomFieldConfig extends BaseFieldConfig {
  custom?: Record<string, unknown>;
}

// //////////////////////////////////////////////////////////////////////////////
//  FIELD CONFIG BY PROVIDER
// //////////////////////////////////////////////////////////////////////////////

export type DBFieldConfig<TProvider extends DBProvider = DBProvider> = TProvider extends 'typeorm'
  ? TypeORMFieldConfig
  : TProvider extends 'sql'
    ? SQLFieldConfig
    : TProvider extends 'mongoose'
      ? MongooseFieldConfig
      : TProvider extends 'mongo'
        ? MongoFieldConfig
        : CustomFieldConfig;

export type EntityDBFields<TEntity, TBase = never, TProvider extends DBProvider = DBProvider> = Partial<
  Record<EntityOwnKey<TEntity, TBase>, DBFieldConfig<TProvider>>
>;

// //////////////////////////////////////////////////////////////////////////////
//  RELATIONS
// //////////////////////////////////////////////////////////////////////////////

export type EntityRelationKind = 'one-to-one' | 'many-to-one' | 'one-to-many' | 'many-to-many';

// Discriminated relation types based on kind
export interface OneToOneRelationConfig {
  kind: 'one-to-one';
  entityMeta: string | EntityMeta;
  module?: string;
  propertyName?: string;
  nullable?: boolean;
  cascade?: boolean | readonly ('insert' | 'update' | 'remove' | 'soft-remove' | 'recover')[];
  eager?: boolean;
  lazy?: boolean;
  joinColumn: string; // Mandatory for one-to-one relations
}

export interface ManyToOneRelationConfig {
  kind: 'many-to-one';
  entityMeta: string | EntityMeta;
  module?: string;
  propertyName?: string;
  nullable?: boolean;
  eager?: boolean;
  lazy?: boolean;
  joinColumn: string; // Mandatory for many-to-one relations
  // cascade is not available for many-to-one relations
}

export interface OneToManyRelationConfig {
  kind: 'one-to-many';
  entityMeta: string | EntityMeta;
  module?: string;
  propertyName?: string;
  cascade?: boolean | readonly ('insert' | 'update' | 'remove' | 'soft-remove' | 'recover')[];
  eager?: boolean;
  lazy?: boolean;
  // joinColumn is not applicable for one-to-many relations
}

export interface ManyToManyRelationConfig {
  kind: 'many-to-many';
  entityMeta: string | EntityMeta;
  module?: string;
  propertyName?: string;
  cascade?: boolean | readonly ('insert' | 'update' | 'remove' | 'soft-remove' | 'recover')[];
  eager?: boolean;
  lazy?: boolean;
  // joinColumn is not applicable for many-to-many relations (uses joinTable instead)
}

export type BaseRelationConfig = OneToOneRelationConfig | ManyToOneRelationConfig | OneToManyRelationConfig | ManyToManyRelationConfig;

export type SQLRelationConfig = BaseRelationConfig & {
  joinColumn?: string;
  inverseJoinColumn?: string;
  referencedColumn?: string;
  inverseSide?: string;
  joinTable?: string | boolean;
  onDelete?: ReferentialAction;
  onUpdate?: ReferentialAction;
  foreignKeyName?: string;
};

export type TypeORMRelationConfig = SQLRelationConfig & {
  typeorm?: {
    relationOptions?: Record<string, unknown>;
    joinColumnOptions?: Record<string, unknown>;
    joinTableOptions?: Record<string, unknown>;
  };
};

export type MongoRelationConfig = BaseRelationConfig & {
  localField?: string;
  foreignField?: string;
  ref?: string;
  refPath?: string;
};

export type MongooseRelationConfig = MongoRelationConfig & {
  mongoose?: {
    populate?: boolean;
    autopopulate?: boolean;
    virtual?: boolean;
    justOne?: boolean;
  };
};

export type DBRelationConfig<TProvider extends DBProvider = DBProvider> = TProvider extends 'typeorm'
  ? TypeORMRelationConfig
  : TProvider extends 'sql'
    ? SQLRelationConfig
    : TProvider extends 'mongoose'
      ? MongooseRelationConfig
      : TProvider extends 'mongo'
        ? MongoRelationConfig
        : BaseRelationConfig & { custom?: Record<string, unknown> };

export type EntityRelations<TEntity, TProvider extends DBProvider = DBProvider> = Partial<
  Record<EntityKey<TEntity>, DBRelationConfig<TProvider>>
>;

// //////////////////////////////////////////////////////////////////////////////
//  INDEXES
// //////////////////////////////////////////////////////////////////////////////

export type IndexOrder = 'ASC' | 'DESC' | 1 | -1 | 'text' | 'hashed';

export type IndexField<TEntity> = EntityKey<TEntity> | readonly [EntityKey<TEntity>, IndexOrder];

export interface EntityIndex<TEntity> {
  fields: readonly IndexField<TEntity>[];
  name?: string;
  unique?: boolean;
  sparse?: boolean;
  background?: boolean;
  expireAfterSeconds?: number;
  where?: string;
  partialFilterExpression?: Record<string, unknown>;
  using?: 'btree' | 'hash' | 'gin' | 'gist' | 'brin' | 'text' | 'custom';
  custom?: Record<string, unknown>;
}

export type EntityIndexes<TEntity> = readonly EntityIndex<TEntity>[];

// //////////////////////////////////////////////////////////////////////////////
//  CHECK CONSTRAINTS
// //////////////////////////////////////////////////////////////////////////////

export interface EntityCheckConstraint {
  name?: string;

  /**
   * Raw DB check expression.
   *
   * Examples:
   *  - "slug <> ''"
   *  - "price >= 0"
   *  - "(is_active = false OR revoked_at IS NULL)"
   */
  expression: string;
}

// //////////////////////////////////////////////////////////////////////////////
//  ENTITY DB TARGETS
// //////////////////////////////////////////////////////////////////////////////

export interface SQLTarget {
  provider: 'sql' | 'typeorm';
  dialect: SQLDialect;
  schema?: string;
  tableName: string;
}

export interface MongoTarget {
  provider: 'mongo' | 'mongoose';
  collectionName: string;
}

export interface CustomTarget {
  provider: 'custom';
  name: string;
  options?: Record<string, unknown>;
}

export type DBTarget = SQLTarget | MongoTarget | CustomTarget;

// //////////////////////////////////////////////////////////////////////////////
//  FULL ENTITY DB DEFINITION
// //////////////////////////////////////////////////////////////////////////////

export interface EntityDBDefinition<TEntity, TBase = never, TProvider extends DBProvider = DBProvider> {
  target: Extract<DBTarget, { provider: TProvider }> | DBTarget;

  fields: EntityDBFields<TEntity, TBase, TProvider>;

  relations?: EntityRelations<TEntity, TProvider>;

  /**
   * DB indexes.
   *
   * Use `unique: true` for unique indexes.
   */
  indexes?: EntityIndexes<TEntity>;

  /**
   * DB-level check constraints.
   */
  checks?: readonly EntityCheckConstraint[];

  options?: {
    timestamps?: boolean;
    softDelete?: boolean;
    versioning?: boolean;
    audit?: boolean;
    multiTenant?: boolean;
    custom?: Record<string, unknown>;
  };
}

// //////////////////////////////////////////////////////////////////////////////
//  HELPERS
// //////////////////////////////////////////////////////////////////////////////

export type InferEntityFromDBDefinition<TDefinition> = TDefinition extends EntityDBDefinition<infer TEntity, any, any> ? TEntity : never;

export type InferProviderFromDBDefinition<TDefinition> =
  TDefinition extends EntityDBDefinition<any, any, infer TProvider> ? TProvider : never;

export type EntityDBDefinitionFor<TEntity, TBase = never> = {
  sql: EntityDBDefinition<TEntity, TBase, 'sql'>;
  typeorm: EntityDBDefinition<TEntity, TBase, 'typeorm'>;
  mongo: EntityDBDefinition<TEntity, TBase, 'mongo'>;
  mongoose: EntityDBDefinition<TEntity, TBase, 'mongoose'>;
  custom: EntityDBDefinition<TEntity, TBase, 'custom'>;
};

export type AnyEntityDBDefinition<TEntity, TBase = never> = EntityDBDefinitionFor<TEntity, TBase>[keyof EntityDBDefinitionFor<
  TEntity,
  TBase
>];
